apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akash-provider-monitor.fullname" . }}-secrets
  labels:
    app: {{ include "akash-provider-monitor.name" . }}
type: Opaque
data:
  SLACK_WEBHOOK_URL: {{ .Values.secrets.SLACK_WEBHOOK_URL | quote }}
  TAILSCALE_API_TOKEN: {{ .Values.secrets.TAILSCALE_API_TOKEN | quote }}
  GRPC_NODE_ADDRESS: {{ .Values.secrets.GRPC_NODE_ADDRESS | quote }}
  SENDGRID_API_KEY: {{ .Values.secrets.SENDGRID_API_KEY | quote }}
  SENDGRID_RECIPIENTS: {{ .Values.secrets.SENDGRID_RECIPIENTS | quote }}
  SENDGRID_EMAIL_SENDER: {{ .Values.secrets.SENDGRID_EMAIL_SENDER | quote }}
