apiVersion: v1
kind: Service
metadata:
  name: {{ include "akash-provider-monitor.fullname" . }}-service
  labels:
    app: {{ include "akash-provider-monitor.name" . }}
    {{- include "akash-provider-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "akash-provider-monitor.name" . }}
